// Generated by scripts/sync-extension-config.mjs. Do not edit directly.
globalThis.SALTBREAD_CONFIG = Object.freeze({
  appUrl: "https://skysh-saltbread.vercel.app",
  appOrigins: ["https://skysh-saltbread.vercel.app","http://localhost:3000"],
  apiBaseUrl: "https://skysh-saltbread.vercel.app",
  dashboardUrl: "https://skysh-saltbread.vercel.app/dashboard",
  detectPath: "/api/ext/detect",
  upbitApiBaseUrl: "https://api.upbit.com",
});
