// Generated by scripts/sync-extension-config.mjs. Do not edit directly.
globalThis.SALTBREAD_CONFIG = Object.freeze({
  appUrl: "http://localhost:3000",
  apiBaseUrl: "http://localhost:3000",
  dashboardUrl: "http://localhost:3000/dashboard",
  detectPath: "/api/ext/detect",
  upbitApiBaseUrl: "https://api.upbit.com",
});
